# Generated by Django 3.2.6 on 2021-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210808_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
